home/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home')
]

posts/urls.py
from django. urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostDeleteView, PostUpdateView

posts_patterns = ([
    path('', PostListView.as_view(), name='posts'),
    path("<int:pk>/<slug:slug>/", PostDetailView.as_view(), name="post"),
    path('create/', PostCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='delete'),
    path('updated/<int:pk>/', PostUpdateView.as_view(), name='update')
], 'posts')

posts_system/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.urls import posts_patterns
from django.conf import settings


urlpatterns = [
    # home urls
    path('', include('home.urls')),
    # posts urls
    path('posts/', include(posts_patterns)),
    path('admin/', admin.site.urls),

    # Auth path
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from .views import SingUpView

urlpatterns = [
    path('signup/', SingUpView.as_view(), name='signup')
]

home/models.py
from django.db import models


# Create your models here.

posts/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
import os

class Post(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = models.TextField(verbose_name="Contenido")
    image = models.ImageField(verbose_name="Imagen", upload_to='posts')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True,
                                   verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['-created']

    def __str__(self):
        return self.title

@receiver(post_delete, sender=Post)
def delete_post_image(sender, instance, **kwargs):
    # Borra la imagen asociada al post al eliminar el post
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

posts/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-title'}),
            'content': forms.Textarea(attrs={'class': 'form-content'}),
        }


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-title'}),
            'content': forms.Textarea(attrs={'class': 'form-content'}),
        }

home/views.py
from django.views.generic.base import TemplateView


# Create your views here.
class HomePageView(TemplateView):
    template_name = 'home/home.html'

posts/views.py
# from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from .models import Post
from .forms import PostCreateForm, PostUpdateForm
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator

# Create your views here.
class PostListView(ListView):
    model = Post


class PostDetailView(DetailView):
    model = Post


@method_decorator(staff_member_required, name="dispatch")
class PostCreateView(CreateView):
    model = Post
    form_class = PostCreateForm

    def get_success_url(self):
            return reverse_lazy('posts:posts') + '?os' 


@method_decorator(staff_member_required, name="dispatch")
class PostDeleteView(DeleteView):
    model = Post

    def get_success_url(self):
            return reverse_lazy('posts:posts') + '?ok' 


@method_decorator(staff_member_required, name="dispatch")
class PostUpdateView(UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name_suffix = "_update_form"


    def get_success_url(self):
            return reverse_lazy('posts:update', args=[self.object.id]) + '?or' 

    def form_valid(self, form):
            instance = form.save(commit=False)

            if 'image' in self.request.FILES:
                instance.image = self.request.FILES['image']

            instance.save()

            return HttpResponseRedirect(self.get_success_url())

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Home{% endblock title %}</title>
    <link href="{% static 'home/style.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <h1><a href="{% url "home" %}">Posts System</a></h1>
        <nav>
            <a href="{% url "home" %}">Home</a>
            <a href="{% url "posts:posts" %}">Posts</a>
            {% if not request.user.is_authenticated %}
              <a class="a-link-login" href="{% url "login" %}">Acceder</a>
            {% else %}
              <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button type="submit" class="a-link-login">Salir</button>
              </form>
            {% endif %}
        </nav>
    </header>
    {% block content %}{% endblock content %}
</body>
</html>

home/templates/home/home.html
{% extends "home/base.html" %}

posts/templates/posts/includes/page_menu.html
{% load static %}

{% if request.user.is_staff %}
<link rel="stylesheet" href="{% static "posts/page.css" %}">
<nav class="my-navbar">
    <div class="my-container">
        <span class="my-navbar-brand"><i>Administrar</i></span>
        <ul class="my-navbar-nav">
            <li class="my-nav-item nav1"><a class="my-nav-link" href="#">Crear página</a></li>
            <li class="my-nav-item"><a class="my-nav-link" href="{% url "posts:posts" %}">
                Listado de páginas
            </a></li>
        </ul>
    </div>
</nav>
{% endif %}

posts/templates/posts/includes/post_menu.html
{% load static %}

{% if request.user.is_staff %}
<link rel="stylesheet" href="{% static "posts/options.css" %}">
<nav class="my-navbar">
    <div class="my-container">
        <span class="my-navbar-brand"><i>Opciones admin</i></span>
        <ul class="my-navbar-nav">
            <!-- FIX -->
            <li class="my-nav-item nav1"><a href="{% url "posts:create" %}" class="btn">Crear post</a></li>
            <li class="my-nav-item"><a href="{% url "posts:posts" %}" class="btn">Listado de posts</a></li>
        </ul>
    </div>
</nav>
{% endif %}

posts/templates/posts/post_confirm_delete.html
{% extends 'home/base.html' %}

{% load static %}
{% block title %}Borrar post{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static "posts/confirm.css" %}">
<main class="confirmation-main">
  <div class="confirmation-container">
    <div class="confirmation-content">
      <form action="" method="post">
        {% csrf_token %}
        <p>¿Estás seguro de que quieres borrar "{{ object }}"?</p>
        <input type="submit" value="Sí, borrar el post" />
      </form>
    </div>
  </div>
</main>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "home/base.html" %}
{% load static %}

{% block title %} {{ post.title }}{% endblock title %}

{% block content %}
  {% include "posts/includes/post_menu.html" %}
  <link rel="stylesheet" href="{% static "posts/detail.css" %}">
  <button class="return"><a href="{% url "posts:posts" %}">volver</a></button>
  <main class="main">
    <div class="container">
      <div class="content">
        <h2>{{post.title}}</h2>
          <p class="text">{{post.content|safe|linebreaksbr}}</p>
        <img src="{{ post.image.url }}">
      </div>
    </div>
  </main>
{% endblock content %}

posts/templates/posts/post_form.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Crear post{% endblock %}

{% block content %}
    {% include 'posts/includes/post_menu.html'%}
    <link rel="stylesheet" href="{% static "posts/forms.css" %}"> 
<main class="main">
    <div class="form-container">
        <form action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Título:</label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="id_content">Contenido:</label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label for="id_image">Imagen:</label>
                {{ form.image }}
            </div>
            <br>
            <input class="form-submit" type="submit" value="Crear post" />
        </form>
    </div>
</main>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "home/base.html" %}
{% load static %}

{% block title %} Posts{% endblock title %}

{% block content %}
	{% include "posts/includes/post_menu.html" %}
	<link rel="stylesheet" href="{% static "posts/style.css" %}">
	{% if 'ok' in request.GET %}
		<p class="msj" style="color:green">
			Posts eliminado correctamente
		</p>
	{% elif 'os' in request.GET %}
	<p class="msj" style="color:green">
    Posts creado correctamente
    </p>
	{% endif %}
	<div class="content_max">
		{% for post in object_list %}
			<section class="post-section">
				<div class="post-content">
					<div class="post-image">
						<img src="{{ post.image.url }}">
					</div>
				</div>
				<div class="post-details">
					<h2>{{ post.title }}</h2>
					<p>{{ post.content|striptags|safe|truncatechars:"100" }}</p>
				</div>
				<div class="btns">
					<button><a href="{% url 'posts:post' post.id post.title|slugify %}">Leer más</a></button>
					{% if request.user.is_staff %}
						<button class="btn-a"><a href="{% url "posts:update" post.id %}">Editar</a></button>
						<button class="btn-a"><a href="{% url "posts:delete" post.id %}">Borrar</a></button>
					{% endif %}
				</div>            
			</section>
		{% endfor %}
	</div>
{% endblock content %}

posts/templates/posts/post_update_form.html
{% extends 'home/base.html' %}
{% load static %}

{% block title %}Actualizar post{% endblock %}

{% block content %}
{% include 'posts/includes/post_menu.html'%}
<link rel="stylesheet" href="{% static "posts/forms.css" %}"> 
<main class="main">
	<div class="form-container">
	  {% if 'or' in request.GET %}
			  <p style="color:green;  margin-bottom:2rem;">
					  Post editado correctamente
					  <a href="{% url "posts:posts" %}">Click aqui para ver el resultado</a>
				  </p>
		  {% endif %}
		<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
			<div class="form-group">
				<label for="id_title">Título:</label>
				{{ form.title }}
		</div>
		<div class="form-group">
				<label for="id_content">Contenido:</label>
				{{ form.content }}
		</div>
		<div class="form-group">
				<label for="id_image">Imagen:</label>
				{{ form.image }}
		</div>
		<br />
			<br>
			<input class="form-submit" type="submit" value="Actualizar post" />
	</form>
</div>
</main>
{% endblock %}